# This workflow will build and deploy a Docker image to DigitalOcean

name: Java (Docker) CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV }}" > src/main/resources/application.yml
          ls -la src/main/resources
          cat src/main/resources/application.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DigitalOcean Container Registry
        run: |
          echo '{"auths":{"registry.digitalocean.com":{"auth":"'${{ secrets.REGISTRY_DOCKER_AUTH }}'"}}}' > $HOME/.docker/config.json

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/pocketurl-registry/pocketurl:latest .
          docker push registry.digitalocean.com/pocketurl-registry/pocketurl:latest

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Run Docker container on Droplet
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.DROPLET_KEY }}
          username: ${{ secrets.DROPLET_USERNAME }}
          passphrase: ${{ secrets.DROPLET_KEY_PASSPHRASE }}

          script: |
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login registry.digitalocean.com -u "${{ secrets.REGISTRY_PASSWORD }}" --password-stdin
            docker pull registry.digitalocean.com/pocketurl-registry/pocketurl:latest
            docker stop pocketurl || true
            docker rm pocketurl || true
            docker run -d -p 80:8080 --name pocketurl registry.digitalocean.com/pocketurl-registry/pocketurl:latest
