# This workflow will build a Java project using Maven
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven    

    - name: Build with Maven
      run: 
        mvn -B package --file pom.xml

    - name: Create Artifacts Directory
      run: mkdir artifacts

    - name: Copy JAR to Artifacts Directory
      run: cp target/*.jar artifacts

    - name: Test with Maven
      run: mvn test    
    
    - name: Save artifact
      uses: actions/upload-artifact@v3
      with:
        name: github-actions-artifact
        path: artifacts
