# This workflow will build and deploy a Docker image to DigitalOcean

name: Java (Docker) CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install doctl
        run: |
          curl -OL https://github.com/digitalocean/doctl/releases/download/v1.98.0/doctl-1.98.0-linux-amd64.tar.gz
          tar xf doctl-1.98.0-linux-amd64.tar.gz
          sudo mv doctl /usr/local/bin

      - name: Login to DigitalOcean Container Registry
        run: |
          doctl registry login --access-token ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/pocketurl-registry/pocketurl:latest .
          docker push registry.digitalocean.com/pocketurl-registry/pocketurl:latest
