# This workflow will build and deploy a Docker image to DigitalOcean

name: Java (Docker) CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up doctl
        run: |
          curl -sL https://github.com/digitalocean/doctl/releases/latest/download/doctl-$(uname -s)-$(uname -m) | sudo tee /usr/local/bin/doctl > /dev/null
          sudo chmod +x /usr/local/bin/doctl
          doctl version

      - name: Authenticate with DigitalOcean
        run: doctl auth init -t ${{ secrets.REGISTRY_PASSWORD }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/pocketurl-registry/pocketurl:latest .
          docker push registry.digitalocean.com/pocketurl-registry/pocketurl:latest
