# This workflow will build and deploy a Docker image to DigitalOcean

name: Java (Docker) CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV }}" > application.yml

      - name: Substitute environment variables in application.yml
        run: envsubst < application.yml > src/main/resources/application.yml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into DigitalOcean Container Registry
        run: |
          echo '{"auths":{"registry.digitalocean.com":{"auth":"'${{ secrets.REGISTRY_DOCKER_AUTH }}'"}}}' > $HOME/.docker/config.json

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/pocketurl-registry/pocketurl:latest .
          docker push registry.digitalocean.com/pocketurl-registry/pocketurl:latest

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DigitalOcean Container Registry
        run: |
          echo '{"auths":{"registry.digitalocean.com":{"auth":"'${{ secrets.REGISTRY_DOCKER_AUTH }}'"}}}' > $HOME/.docker/config.json

      - name: Pull Docker image
        run: docker pull registry.digitalocean.com/pocketurl-registry/pocketurl:latest

      - name: Run Docker container on Droplet
        env:
          DOCKER_IMAGE: registry.digitalocean.com/pocketurl-registry/pocketurl:latest
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DROPLET_IP }}
          key: ${{ secrets.DROPLET_KEY }}
          username: ${{ secrets.DROPLET_USERNAME }}
          passphrase: ${{ secrets.DROPLET_KEY_PASSPHRASE }}

          script: |
            chmod +x deploy_script.sh
            ./deploy_script.sh
